<?php

namespace Tests\Feature;

use App\Models\Department;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class DepartmentTest extends TestCase
{
//    use RefreshDatabase;
    /**
     * A basic feature test example.
     */
//    private $user;
//    protected function setUp(): void
//    {
//        parent::setUp(); // TODO: Change the autogenerated stub
//        $admin = User::first();
//        $this->user = $this->actingAs($admin);
//    }

    public function test_departments(): void
    {
//        $department = Department::create([
//           'name' => ['en' => 'laps', 'ar' => 'لاب'],
//           'image' => 'image.png'
//        ]);

//        $this->assertEquals('لاب', $department->getTranslation('name','ar'));
        $department = Department::get();
        $this->assertDatabaseCount('departments', 3);

    }

    public function test_store_data_in_departments()
    {
        //$response = $this->actingAs($this->user)
            $response = Department::create(['name' => ['en' => 'Labs', 'ar' => 'لابات'], 'image' => 'image.png']);
        $this->assertDatabaseCount('departments', 1);
    }
}
